---
title: "Asteraceae_Trabajo_Entregar"
author: "Raymond L. Tremblay"
date: "3/3/2022"
output:
  html_document:
    css: Lab_Ecol_Gen.css
    fig_caption: yes
    highlight: pygments
#  theme: simplex   To have the TOC in Red
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

## Trabajo de campo

Cada grupo de estudiante de (3-4 estudiante) recojio datos sobre una planta en un pastizal En Humacao. Esta planta una especies de la familiua Asteraceae, el genero _____, especies _____.   

Los datos recopilado fueron 

 - un indice de **esfuerzo reproductivo**, el número de inflorescencia 

 - una variable morfológica que *pudiese* ser seleccionado y tener una ventaja evolutiva.
    - El número de tallos
    - El número de hojas
    - El ancho de la hoja más ancha
    - El El largo del tallo más largo
 
***

## El tema del Trabajo.

Su trabajo escrito en formato de artículo cientifico se enfocará en la **selección fenotípica**.  El en trabajo que se hizo nosotros no podemos decir que es **seleción natural**, por que no tenemos evidencia de que la **variación morfologica** es un resultado de la genética.  

Ud hará una busqueda de literatura grande (evaluará por lo menos 30 articulos), y citará por lo menos 15 articulos en su trabajo escrito.

***

## Preguntas que pueden evaluar

 - ¿Hay evidencia en otras especies de plantas que la variable morfológica que UD evaluo tiene ventaja como sus analisis han demostrado?
 - ¿Cuan diferentes son el coeficiente **m** en otras especies que evaluarón la misma variable, son positivos, negativos, cuadraticos?
 - ¿Cual es el coefficente de **m** en otras especies, es más grande, más pequeño, igual como lo que uds observarón? 
 - etc
 
 
***

## El formato del Escrito

El Estilo del trabajo seguira el formato de la revista **Biotropica**


Ejemplo vea el siguiente enlace. [Biotropica](PDF/Biotropica - 2021 - Power - Even small forest patches increase bee visits to flowers in an oil palm plantation landscape.pdf) 

NOTA: que este articulo sigue la organización como hemos discutido en una clase anterior en el modulo [Escribir un Articulo](https://raymondltremblay.github.io/Lab_Ecol_General/Escribir_Articulos.html). 



## Guia para escribir su trabajo

1. Resumen: 1/2 pagina
2. Introducción: 2 paginas
3. Metodología: 1/3 a 1/2 pagina
4. Resultados: 1/3 a 1/2 pagina
5. Discución: 2-3 paginas
6. Referencias: TODAS (Esta sección no esta incluida en la 6-7 paginas mencionada ariba:  NOTA BIEN EL ESTILO de este articulo)
7. Contribución de cada autor


***


Vea la plantilla de distribución de puntos por sección [aquí]()
 
 
 
 

