---
title: "Exponential_model"
author: "RLT"
date: "11/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
A <- structure(list(Time = c(0, 1, 2, 4, 6, 8, 9, 10, 11, 12, 13, 
14, 15, 16, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30), 
Counts = c(126.6, 101.8, 71.6, 101.6, 68.1, 62.9, 45.5, 41.9, 
46.3, 34.1, 38.2, 41.7, 24.7, 41.5, 36.6, 19.6, 
22.8, 29.6, 23.5, 15.3, 13.4, 26.8, 9.8, 18.8, 25.9, 19.3)), .Names = c("Time", "Counts"), row.names = c(1L, 2L,
3L, 5L, 7L, 9L, 10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 19L, 20L, 21L, 22L, 23L, 25L, 26L, 27L, 28L, 29L, 30L,
31L), class = "data.frame")
```

```{r}
attach(A)
names(A)
```

```{r}
exponential.model <- lm(log(Counts)~ Time)
summary(exponential.model)






```

```{r}
timevalues <- seq(0, 30, 0.1)
Counts.exponential2 <- exp(predict(exponential.model,list(Time=timevalues)))
plot(Time, Counts,pch=16)
lines(timevalues, Counts.exponential2,lwd=2, col = "red", xlab = "Time (s)", ylab = "Counts")



library(ggplot2)

ggplot(A, aes(Time, Counts))+
  geom_smooth(method=lm, colour="blue")+
  geom_smooth(aes(), method = "lm", formula = y ~ poly(x+1,2), 
              color ="red", se =TRUE, size = 1)+
  geom_smooth(aes(), method = "lm", formula = y ~ log(x+1), 
              color ="orange", se =TRUE, size = 1)

```


```{r}
model1=glm(Counts~Time, family=Gamma(link="log"), data = A)
summary(model1)
```


